- name: Create SVM
  na_ontap_svm:
    state: present
    name: "{{ item.svm_name }}"
    root_volume: "{{ item.root_vol }}"
    root_volume_aggregate: "{{item.rootvol_aggregate }}" 
    root_volume_security_style: "{{ item.root_vol_sec_style }}"
    allowed_protocols: "{{ item.protocols }}" 
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ SVMs }}"

- name: Create file data LIF
  na_ontap_interface:
    state: present
    interface_name: "{{ item.LIF_Name }}" 
    home_port: "{{ item.LIF_home_port }}" 
    home_node: "{{ item.LIF_home_node }}" 
    role: "{{ item.LIF_Role }}"
    protocols: "{{ item.LIF_Protocol }}"
    address: "{{ item.LIF_IP }}"
    netmask: "{{ LIF_netmask }}"
    vserver: "{{ item.svm_lif }}" 
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ Create_LIFS }}" 

- name: Create Route
  na_ontap_net_routes:
    state: present
    destination: "{{ item.Destination }}"
    gateway: "{{ item.Gateway }}"
    metric: "{{ item.Metric }}"
    vserver: "{{ item.Which_SVM }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ Create_Routes }}"

- name: Create ExportPolicyRule
  na_ontap_export_policy_rule:
    state: present
    policy_name: default
    vserver: "{{ item.svm_name }}" 
    client_match: 192.168.0.0/16
    ro_rule: any
    rw_rule: any
    protocol: any
    super_user_security: any
    allow_suid: true
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ SVMs }}"  

- name: enable NFS
  na_ontap_nfs:
    state: present
    service_state: started
    vserver: "{{ item.svm_name }}" 
    nfsv3: enabled
    nfsv4: disabled
    nfsv41: disabled
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ SVMs }}"

- name: Create FlexVols 
  na_ontap_volume:
    state: present
    name: "{{ item.Name }}"    
    is_infinite: False
    aggregate_name: "{{ item.aggregate_for_vol }}"
    size: "{{ item.Size }}"
    size_unit: gb         
    vserver: "{{ item.Which_SVM }}" 
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ Volumes }}"
 
- name: Mount volumes to Junction Path
  na_ontap_command:
    command: volume mount -vserver "{{ item.SVM }}" -volume "{{ item.volume }}" -junction-path "{{ item.junction }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ Junction_Mount }}"
