
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ansible-content
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: sc-for-ansible
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ansible-ssh
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: sc-for-ansible