apiVersion: v1
kind: Secret
metadata:
  name: ansible-for-jenkins-secret
  namespace: ansible
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: ansible
secrets:
- name: ansible-for-jenkins-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ansible-role-binding-for-jenkins
  namespace: ansible
subjects:
- kind: ServiceAccount
  name: ansible-for-jenkins
  namespace: ansible
roleRef:
  kind: Role
  name: ansible-role-for-jenkins
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ansible-role-for-jenkins
  namespace: ansible
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete","list","get"]
