---
- name: Deploy ONTAP Cluster config
  hosts: localhost
  collections:
    - netapp.ontap
  roles:
    - role: /etc/ansible/LabAnsible/LabAnsibleDockerSimple/2-cluster

- name: Mount export to rhel
  hosts: rhel
  roles:  
    - role: /etc/ansible/LabAnsible/LabAnsibleDockerSimple/2-mount_nfs