---
- name: Unmount the NFS shares
  mount:
    path: "/mnt/{{ item.get ('local_volume') }}"
    state: unmounted
  with_items: "{{ Mount_NFS }}"

- name: Delete the directories
  file:
    path: "/mnt/{{ item.get ('local_volume') }}"
    state: absent
  with_items: "{{ Mount_NFS }}"

- name: Delete FlexVol
  na_ontap_volume:
    state: absent
    name: "{{ item.Name }}"
    vserver: "{{ item.Which_SVM }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  with_items: "{{ Volumes }}"

- name: Delete SVM
  na_ontap_svm:
    state: absent
    name: "{{ item.svm_name }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
  with_items: "{{ SVMs }}"
