
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ansible-content
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: storage-class-nas
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ansible-ssh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: storage-class-nas