---
- name: Unmap LUNs
  netapp.ontap.na_ontap_lun_map:
    state: absent
    initiator_group_name: "{{ item.igroup }}"
    path: "/vol/{{ item.vol_name }}/{{ item.name }}"
    vserver: "{{ item.svm_name }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items:
    "{{ luns }}"
  when: luns != None

- name: Delete iGroups
  netapp.ontap.na_ontap_igroup:
    state: absent
    name: "{{ item.igroup_name }}"
    vserver: "{{ item.svm_name }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ igroups }}"
  when: igroups != None

- name: Delete FlexVol
  netapp.ontap.na_ontap_volume:
    state: absent
    name: "{{ item.Name }}"
    vserver: "{{ item.Which_SVM }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ Volumes }}"

- name: Delete SVM
  netapp.ontap.na_ontap_svm:
    state: absent
    name: "{{ item.svm_name }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: false
  with_items: "{{ SVMs }}"
