---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Move FlexVol
  tasks:
  - name: move flexvol
    netapp.ontap.na_ontap_volume:
     state: present
     name: flex_test
     aggregate_name: aggr2
     vserver: nfs_svm
     hostname: 192.168.0.101
     username: admin 
     password: Netapp1!
     https: true
     validate_certs: false
     