---
- hosts: localhost
  collections:
    - netapp.ontap

  vars:
    param: &param
      vserver: nfs_svm
      hostname: 192.168.0.101
      username: admin 
      password: Netapp1!
      https: true
      validate_certs: false

  name: Create Volume & Snapshot
  tasks:
  - name: Create Snapshot Policy
    na_ontap_snapshot_policy:
     state: present
     name: ansible_policy
     comment: "policy created via ansible"
     schedule: ['hourly', 'daily', 'weekly', 'monthly', '5min']
     count: [1, 2, 3, 4, 5]
     enabled: True
     <<: *param

  - name: Create Flexvol
    na_ontap_volume:
     state: present
     name: ansible_vol
     aggregate_name: aggr1
     size: 1
     size_unit: gb
     junction_path: /ansible
     snapshot_policy: ansible_policy
     <<: *param

  - name: Create Snapshot 
    na_ontap_snapshot:
     state: present
     snapshot: ansible_snap
     volume: ansible_vol
     comment: "snap created by ansible"
     <<: *param

  - name: Retrieve information
    na_ontap_info: 
     state: info
     gather_subset: 
       - snapshot_policy_info
       - snapshot_info
     <<: *param
    register: ontap_info
  - debug:
      msg: "{{ ontap_info.ontap_info }}"