---
- hosts: localhost
  collections:
    - netapp.ontap

  vars:
    param: &param
      vserver: svm1
      hostname: 192.168.0.101
      username: admin 
      password: Netapp1!
      https: true
      validate_certs: false

  name: Volume & Snapshot Policy cleanup
  tasks:
  - name: Delete Flexvol
    na_ontap_volume:
     state: absent
     name: ansible_vol
     <<: *param

  - name: Delete Snapshot Policy
    na_ontap_snapshot_policy:
     state: absent
     name: ansible_policy
     <<: *param